logLevel = "DEBUG"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[web]
address = ":8080"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.local"
swarmmode = true
watch = true
exposedbydefault = false

[acme]
email = "badoyutiti@tech69.com"
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
OnHostRule = true